# Colors (Srcery)
colors:
  # Default colors
  primary:
    background: '0x1c1b19'
    foreground: '0xfce8c3'

  # Normal colors
  normal:
    black:   '0x1c1b19'
    red:     '0xef2f27'
    green:   '0x519f50'
    yellow:  '0xfbb829'
    blue:    '0x2c78bf'
    magenta: '0xe02c6d'
    cyan:    '0x0aaeb3'
    white:   '0xd0bfa1'

  # Bright colors
  bright:
    black:   '0x918175'
    red:     '0xf75341'
    green:   '0x98bc37'
    yellow:  '0xfed06e'
    blue:    '0x68a8e4'
    magenta: '0xff5c8f'
    cyan:    '0x53fde9'
    white:   '0xfce8c3'

cursor:
  style: Block
  unfocused_hollow: true

font:
  normal:
    family: 'BlexMono Nerd Font Mono'
    style: Text
  bold:
    family: 'BlexMono Nerd Font Mono'
    style: Bold
  italic:
    family: 'BlexMono Nerd Font Mono'
    style: Italic
  size: 15.0
<<<<<<< HEAD:alacritty/alacritty.yml
=======
    # use_thin_strokes: true

# shell:
#   program: /bin/zsh
  # args:
  #   - -l
  #   - -c
# - "tat"
>>>>>>> 09ccdbfbff7a929d6546490849f2a155153256fc:alacritty/.alacritty.yml

window:
  padding:
    x: 10
    y: 10
<<<<<<< HEAD:alacritty/alacritty.yml

key_bindings:
  - { key: C, mods: Alt, chars: "\x1bc" }
=======
  option_as_alt: Both

    # key_bindings:
    # - { key: C, mode: Alt, chars: "\x0bf" }
>>>>>>> 09ccdbfbff7a929d6546490849f2a155153256fc:alacritty/.alacritty.yml
