[colors.primary]
background = "#1c1b19"
foreground = "#fce8c3"

[colors.cursor]
text = "CellBackground"
cursor = "#fbb829"

[colors.normal]
black = "#1c1b19"
red = "#ef2f27"
green = "#519f50"
yellow = "#fbb829"
blue = "#2c78bf"
magenta = "#e02c6d"
cyan = "#0aaeb3"
white = "#baa67f"

[colors.bright]
black = "#918175"
red = "#f75341"
green = "#98bc37"
yellow = "#fed06e"
blue = "#68a8e4"
magenta = "#ff5c8f"
cyan = "#2be4d0"
white = "#fce8c3"

[cursor]
style = "Beam"
unfocused_hollow = true
thickness = 0.16

[font]
size = 15.0

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Text"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[window.padding]
x = 10
y = 10
