#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export FZF_ALT_C_COMMAND='fd -t d . $HOME'
export FZF_DEFAULT_COMMAND='fd --type f'

export NVM_DIR="/Users/treycaliva/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/treycaliva/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/treycaliva/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/treycaliva/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/treycaliva/google-cloud-sdk/completion.zsh.inc'; fi

# source ~/.iterm2_shell_integration.zsh
export PATH="/usr/local/anaconda3/bin:$PATH"
chruby ruby-2.7.1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
